name: "Trigger Integration tests"
on:
  pull_request:
      
jobs: 
  trigger-integration-tests:
    name: Trigger Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
            path: IntegrationTests

      - name: Always pass
        if: false
        run: echo "Hello"
    
        
