name: "Run unit tests."
on: # rebuild any PRs and main branch changes
  pull_request:
#     branches:
#      - main

jobs:
  build: # make sure build/ci works properly
    if: ${{ vars.PRETTIFY_JS == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Running L0 tests.
        run: |
          npm install
          npm test
